# -*- coding: utf-8 -*-
"""audit_engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sPYZ_HSbIaKhsVtkGFM3S0YGD10dS10H
"""

# ==============================================================================
# PROJECT: AUTOMATED INTERNAL AUDIT ENGINE
# Description: Automated detection of expense anomalies (Weekend, Structuring, Duplicates)
# ==============================================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from fpdf import FPDF
import xlsxwriter
from datetime import datetime
import os

# 1. SETUP ENVIRONMENT
if not os.path.exists('audit_charts'): os.makedirs('audit_charts')

print("📥 Loading Client Data...")
try:
    df = pd.read_csv('Raw_Expense_Data.csv')
    df['Date'] = pd.to_datetime(df['Date'])
    print(f"✅ Data Loaded Successfully: {len(df)} transactions.")
except FileNotFoundError:
    print("❌ Error: File 'Raw_Expense_Data.csv' not found. Please verify data path.")
    exit()

# ==============================================================================
# PHASE 1: AUDIT LOGIC ENGINE (CORE)
# ==============================================================================
print("🔍 Running Audit Rules...")

df['Is_Weekend'] = df['Date'].dt.dayofweek >= 5
df['Audit_Finding'] = 'Pass' # Mặc định là Pass

# RULE 1: WEEKEND VIOLATION
# Logic: Chi tiêu vào T7, CN tại các merchant nhạy cảm (Meals, Entertainment)
mask_weekend = (df['Is_Weekend'] == True) & (df['Category'].isin(['Meals', 'Entertainment']))
df.loc[mask_weekend, 'Audit_Finding'] = 'Weekend Violation'

# RULE 2: STRUCTURING (SPLIT PO)
# Logic: Cùng 1 người, cùng 1 ngày, cùng 1 Merchant, tổng tiền > 8000 (mà mỗi món < 5000)
# (Đây là hành vi chia nhỏ để né hạn mức duyệt 5000$)
df['Date_Str'] = df['Date'].astype(str)
structuring_check = df.groupby(['EmployeeID', 'Date_Str', 'Merchant'])['Amount'].sum().reset_index()
structuring_check.rename(columns={'Amount': 'Total_Daily_Spend'}, inplace=True)
suspicious_structuring = structuring_check[structuring_check['Total_Daily_Spend'] > 8000]

# Flag lại vào bảng gốc
keys = list(zip(suspicious_structuring.EmployeeID, suspicious_structuring.Date_Str, suspicious_structuring.Merchant))
def check_structuring(row):
    if (row['EmployeeID'], str(row['Date'].date()), row['Merchant']) in keys and row['Audit_Finding'] == 'Pass':
        return 'High Value / Split Risk'
    return row['Audit_Finding']

df['Audit_Finding'] = df.apply(check_structuring, axis=1)

# RULE 3: DUPLICATE CLAIMS
# Logic: Cùng số tiền, cùng Merchant
duplicates = df[df.duplicated(subset=['Amount', 'Merchant', 'EmployeeID'], keep=False)]
df.loc[duplicates.index, 'Audit_Finding'] = 'Duplicate Claim'

# Tách riêng dữ liệu gian lận để báo cáo
fraud_only = df[df['Audit_Finding'] != 'Pass'].copy()
print(f"⚠️ DETECTED: {len(fraud_only)} High-Risk Transactions.")

# ==============================================================================
# PHASE 2: VISUALIZATION GENERATION
# ==============================================================================
print("📊 Generating Visualizations...")

# Chart 1: Findings by Category
plt.figure(figsize=(10, 6))
sns.countplot(y='Category', data=fraud_only, order=fraud_only['Category'].value_counts().index, palette='Reds_r')
plt.title('High-Risk Transactions by Category')
plt.tight_layout()
plt.savefig('audit_charts/chart_category.png')
plt.close()

# Chart 2: Finding Type Distribution
plt.figure(figsize=(8, 8))
fraud_counts = fraud_only['Audit_Finding'].value_counts()
plt.pie(fraud_counts, labels=fraud_counts.index, autopct='%1.1f%%', colors=['#ff9999','#66b3ff','#99ff99'])
plt.title('Distribution of Audit Findings')
plt.savefig('audit_charts/chart_pie.png')
plt.close()

# ==============================================================================
# PHASE 3: REPORTING (PDF & EXCEL)
# ==============================================================================
print("📝 Compiling Final Reports...")

# A. EXCEL DASHBOARD (Interactive)
writer = pd.ExcelWriter('Audit_Report_Dashboard.xlsx', engine='xlsxwriter')
fraud_only.to_excel(writer, sheet_name='Detailed_Audit_Log', index=False)

# Tạo Dashboard sheet (đơn giản)
workbook = writer.book
worksheet = workbook.add_worksheet('Dashboard')
worksheet.write('A1', 'Total High Risk Transactions:')
worksheet.write('B1', len(fraud_only))
worksheet.write('A2', 'Total Potential Leakage ($):')
worksheet.write('B2', fraud_only['Amount'].sum())

writer.close()

# B. PDF EXECUTIVE REPORT
class PDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'INTERNAL AUDIT REPORT: EXPENSE CONTROL', 0, 1, 'C')
        self.ln(5)

    def chapter_title(self, title):
        self.set_font('Arial', 'B', 12)
        self.set_fill_color(200, 220, 255)
        self.cell(0, 10, title, 0, 1, 'L', 1)
        self.ln(4)

    def body_text(self, txt):
        self.set_font('Arial', '', 11)
        self.multi_cell(0, 5, txt)
        self.ln()

pdf = PDF()
pdf.add_page()

# Executive Summary
pdf.chapter_title('1. EXECUTIVE SUMMARY')
summary_text = (f"This automated audit engagement has reviewed {len(df)} transactions. "
                f"We identified {len(fraud_only)} exceptions with a total potential risk value of ${fraud_only['Amount'].sum():,.2f}.\n\n"
                "The primary control weaknesses detected include Weekend Policy Violations and potential Structuring of high-value assets.")
pdf.body_text(summary_text)

# Visuals
pdf.chapter_title('2. RISK VISUALIZATION')
pdf.image('audit_charts/chart_pie.png', x=10, w=90)
pdf.image('audit_charts/chart_category.png', x=110, y=None, w=90)
pdf.ln(90) # Move cursor down

# Detailed Findings Table (Top 10)
pdf.add_page()
pdf.chapter_title('3. DETAILED FINDINGS (SAMPLE TOP 15)')
pdf.set_font('Arial', 'B', 9)
pdf.cell(25, 8, 'Date', 1)
pdf.cell(20, 8, 'EmpID', 1)
pdf.cell(30, 8, 'Category', 1)
pdf.cell(25, 8, 'Amount', 1)
pdf.cell(40, 8, 'Finding', 1)
pdf.ln()

pdf.set_font('Arial', '', 9)
for i, row in fraud_only.head(15).iterrows():
    pdf.cell(25, 8, str(row['Date'].date()), 1)
    pdf.cell(20, 8, str(row['EmployeeID']), 1)
    pdf.cell(30, 8, str(row['Category']), 1)
    pdf.cell(25, 8, f"${row['Amount']:,.2f}", 1)
    pdf.cell(40, 8, str(row['Audit_Finding']), 1)
    pdf.ln()

pdf.output('Audit_Report_Final_Professional.pdf', 'F')
print("✅ DONE! Reports generated successfully.")