# -*- coding: utf-8 -*-
"""data_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PffdCAmYrLr-hVcxFrGZo_kOP4EXi7LO
"""

# ---------------------------------------------------------
# MỤC ĐÍCH: GIẢ LẬP DỮ LIỆU GIAN LẬN ĐỂ TEST HỆ THỐNG AUDIT
# (File này chỉ dùng nội bộ để sinh dữ liệu test)
# ---------------------------------------------------------

import pandas as pd
import numpy as np
import random
from faker import Faker
from datetime import datetime, timedelta

# 1. SETUP
fake = Faker('en_US')
np.random.seed(2025)

print("🚀 Đang khởi tạo dữ liệu giả lập (Simulation)...")

expense_logic = {
    'Travel': {'merchants': ['Uber', 'Lyft', 'Delta Air', 'United', 'Hertz', 'Amtrak'], 'range': (30, 1500)},
    'Meals': {'merchants': ['Starbucks', 'McDonalds', 'The Night Club', 'Fancy Steakhouse'], 'range': (10, 500)},
    'Office': {'merchants': ['Staples', 'Amazon Biz', 'BestBuy', 'Office Depot'], 'range': (50, 2000)},
    'IT Hardware': {'merchants': ['Apple Store', 'Dell', 'Lenovo', 'Newegg'], 'range': (500, 5000)},
    'Software': {'merchants': ['Adobe', 'Salesforce', 'AWS', 'Atlassian'], 'range': (100, 5000)},
    'Lodging': {'merchants': ['Marriott', 'Hilton', 'Airbnb', 'Hyatt'], 'range': (100, 3000)}
}

# Create 12k data
data = []
start_date = datetime(2023, 1, 1)
employees = [f"EMP{str(i).zfill(3)}" for i in range(1, 151)]

for _ in range(12000):
    cat = random.choice(list(expense_logic.keys()))
    date = start_date + timedelta(days=random.randint(0, 365*3))

    # 95% normal transactions (Weekday)
    if date.weekday() >= 5:
        if random.random() > 0.1:
            date = date - timedelta(days=2)

    row = {
        'Date': date,
        'EmployeeID': random.choice(employees),
        'Category': cat,
        'Amount': round(random.uniform(*expense_logic[cat]['range']), 2),
        'Merchant': random.choice(expense_logic[cat]['merchants']),
        'Description': 'Business Expense'
    }
    data.append(row)

# ---------------------------------------------------------
# INJECT FRAUD SCENARIOS
# ---------------------------------------------------------

# Weekend Violation
for _ in range(200):
    data.append({
        'Date': datetime(2023, 11, 11), # Thứ 7
        'EmployeeID': random.choice(employees),
        'Category': 'Meals',
        'Amount': round(random.uniform(100, 3500), 2),
        'Merchant': 'The Night Club',
        'Description': 'Personal Weekend Dinner'
    })

# Structuring (Split bill > 5000$)
target_emp = random.choice(employees)
audit_date = datetime(2023, 12, 1)
for part in ['Part A', 'Part B']:
    data.append({
        'Date': audit_date,
        'EmployeeID': target_emp,
        'Category': 'IT Hardware',
        'Amount': 4900.00, # Threshold: 5000
        'Merchant': 'Apple Store',
        'Description': f'Macbook Pro {part}'
    })

# Duplicate Claims
dup_emp = random.choice(employees)
dup_amt = 1250.55
for _ in range(2):
    data.append({
        'Date': datetime(2024, 5, 15),
        'EmployeeID': dup_emp,
        'Category': 'Travel',
        'Amount': dup_amt,
        'Merchant': 'Delta Air',
        'Description': 'Flight to NY'
    })

# Export CSV
df = pd.DataFrame(data)
df['Date'] = pd.to_datetime(df['Date']).dt.date
df.to_csv('Raw_Expense_Data.csv', index=False)

print(f"✅ Đã tạo xong file 'Raw_Expense_Data.csv' với {len(df)} dòng.")
print("👉 Giờ hãy chạy file audit_engine.py để quét file này.")